services:
  db:
    image: postgres
    env_file: ".env"
    environment:
      - POSTGRES_USER=${LOGIN_DB}
      - POSTGRES_PASSWORD=${PASSWORD_DB}
      - POSTGRES_DB=service
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app_net
    command: [ "postgres", "-c", "log_destination=stderr", "-c", "logging_collector=on", "-c", "log_directory=/var/log/postgresql" ]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${LOGIN_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
    env_file:
      - ".env"
    ports:
      - "8080:8080"
    networks:
      - app_net
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./logs:/logs
networks:
  app_net:

volumes:
  postgres_data: